export const ADD_TO_CART = 'ADD_TO_CART';
export const UPDATE_ITEM_CARD = 'UPDATE_ITEM_CARD';
export const DELETE_ITEM = 'DELETE_ITEM';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';